name: Documentation Update

on:
  push:
  pull_request:

jobs:
  docs:
    name: "Documentation"
    uses: pcdshub/pcds-ci-helpers/.github/workflows/python-docs.yml@master
    with:
      deploy: ${{ github.repository_owner == inputs.docs-organization && (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags')) }}
      package-name: ""
      install-package: false
      # docs-template-repo: "pcdshub/twincat-docs-template"
      # docs-template-ref: "master"
      requirements-files: "requirements.txt"
