name: Documentation Update

on:
  push:
  pull_request:
  schedule:
    # Run at 2AM daily:
    - cron: '0 2 * * *'

jobs:
  docs:
    name: "Documentation"
    uses: klauer/pcds-ci-helpers/.github/workflows/python-docs.yml@enh_timeout_minutes
    with:
      deploy: ${{ github.repository_owner == 'pcdshub' && (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags')) }}
      # There's no package to install here:
      package-name: ""
      install-package: false
      requirements-files: "requirements.txt"
      timeout-minutes: 720
